### ISSUE TITLE
definitions of bulk density v gross bulk density

### ISSUE THREAD

**Issue by meganrwong** [ANZSoilData/spmile#10]
bulk density is the mass of bulk material in a given volume
Clarifying - How does property bulk density differ from gross bulk density? 

methods 503.01 - 0.4 in the brown book exclude the coarse fragment fraction of soil  - this measures observed property bulk density
wheras
method 503.05 'Soil with coarse fragments: Gross bulk density (fine earth and course fragments)' - measures observed property gross bulk density'. 
Right?

@ljgregory @GGrealish @abhritchie

**Comment by GGrealish** [comment]
I don't have a brown book to check - is it online somewhere to download?
from what you have written seems like
gross BD is the whole (fine and coarse) - from my way of thinking that could be obtained using a core
property BD looks like they have picked out the coarse frags - I suspect this would be a repacked core of fine earth.

But would need to read the methods to confirm

**Comment by meganrwong** [comment]
Thanks Gerard. 

I re-read the method 503.01 - 0.4 . They don't have coarse frags removed (whole cores, no sieving). It is just that these methods read as not recommended for soils with coarse frags. Method 503.05 is recommended for soils with coarse frags. 

So, here 'bulk density' and 'gross bulk density' seem to be talking about the same property (the mass of bulk material in a given volume-  of whole soil (coarse and fine fractions).

Unless your library has, you purchase from here if interested https://www.publish.csiro.au/book/3147/

**Comment by meganrwong** [comment]
Can't see that there is something to fix here in the vocab. Closing
