### ISSUE TITLE
Research Vocabs Australia - Demo to live

### ISSUE THREAD

**Issue by meganrwong** [ANZSoilData/spmile#14]

**Comment by meganrwong** [comment]
done https://vocabs.ardc.edu.au/viewById/648
@ljgregory @abhritchie @dr-shorthair

**Comment by dr-shorthair** [comment]
Not fully live until @ljgregory has done the redirects ;-) 

e.g. `http://anzsoil.org/def/au/spm/spmile/510.02` 
--> `http://vocabs.ardc.edu.au/repository/api/lda/csiro-ansis/soil-physical-measurements/1-0-2023-04-21/resource?uri=http://anzsoil.org/def/au/spm/spmile/510.02`

**Comment by meganrwong** [comment]
true true @dr-shorthair I just got a bit eager

**Comment by meganrwong** [comment]
Done. This is out of demo, in RVA with re-directs set up. 
https://vocabs.ardc.edu.au/viewById/648
eg pellence
http://anzsoil.org/def/au/spm/spmile/505
